### ISSUE TITLE
BINANCE_ENCRYPTED_USER_ID

### ISSUE THREAD

**Issue by crysan** [spartanz51/binance_leaderboard_listener#1]
Hi!
From where you need to take BINANCE_ENCRYPTED_USER_ID ?

**Comment by ghost** [comment]
in url, example https://www.binance.com/en/futures-activity/leaderboard?type=myProfile&tradeType=PERPETUAL&encryptedUid=CA7AC7A51569D13B0F57A875521972F3.

encryptedUid is userID
