### ISSUE TITLE
Reponse example

### ISSUE THREAD

**Issue by ljs19923** [spartanz51/binance_leaderboard_listener#3]
Hi, can you provide an example of responses? Is it possible to get all open positions from this call?
Thanks

**Comment by spartanz51** [comment]
Hello,


> can you provide an example of responses?

Here's an example of event you get:

```
[
  {
    symbol: 'BTCUSDT',
    entryPrice: 23857.47745515,
    markPrice: 23693.23612848,
    pnl: -646.61810309,
    roe: -0.56656284,
    updateTime: [ 2023, 2, 22, 17, 20, 11, 925000000 ],
    amount: 3.937,
    updateTimeStamp: 1677086411925,
    yellow: true,
    tradeBefore: false,
    leverage: 100
  }
]
```


> Is it possible to get all open positions from this call?

Yes, it shows every opened position
