### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by mozhn** [spartanz51/binance_leaderboard_listener#4]
Hello, thanks for this plugin. How can I find out the rate limit?

**Comment by spartanz51** [comment]
Hello, the rate limit information is available on the [Binance Perpetual Api documentation](https://www.binance.com/en/support/faq/rate-limits-on-binance-futures-281596e222414cdd9051664ea621cdc3)

>Binance Futures provides rate limit adjustment flexibility via a volume-based tier system. The default rate limit per IP is 2,400/min, and the default order limit per account/sub-account is 1,200/min.
